### ISSUE TITLE
End date has to be before start date

### ISSUE THREAD

**Issue by fabianmossberg** [agneym/calendar-url-ui#11]
On the demo, end date has to be before start date.

It should probably be the other way around. Also, whatever I chose in this box, this warning never disappears.

<img width="430" alt="Screenshot 2020-09-23 at 15 01 44" src="https://user-images.githubusercontent.com/1999142/94015935-cab12d00-fdad-11ea-8f99-db4e33314367.png">

**Comment by TaarnStar** [comment]
Hi, I would like to tackle this issue if it is still relevant.

**Comment by agneym** [comment]
Hey @TaarnStar ! 

This is a very old issue, the repo is not actively maintained. Thanks for the interest.
